Fix broken github/updatecli actions
Updatecli actions have been skipped due to an incorrect branch name configuration:

```
ERROR: something went wrong in "target#dockerfile" : something went wrong in target "dockerfile" : "reference not found"

Pipeline "Update build base version" failed
Skipping due to:
something went wrong during target execution
```

Fixup: afd5b193aff1d7b3f71de640711863f5b767ace1
Signed-off-by: Michael Fritch <mfritch@suse.com>