Fix-up broken updatecli github action
Updatecli actions have been skipped due to an incorrect branch name configuration:

```
ERROR: something went wrong in "target#dockerfile" : something went wrong in target "dockerfile" : "reference not found"

Pipeline "Update build base version" failed
Skipping due to:
        something went wrong during target execution
```

Signed-off-by: Michael Fritch <mfritch@suse.com>